# Machine Learning Zoomcamp

## 1.7 Introduction to NumPy — Practice

Work through each exercise from memory before running it. If you get stuck, peek at the corresponding
section in the solution notebook: `07-numpy.ipynb` (same folder).

Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [2]:
# Import numpy under its usual alias
import numpy as np

## Creating arrays

1. Create an array of 10 zeros.
2. Create an array of 10 ones.
3. Create an array of 10 elements, all equal to `2.5`, using a single function call (not multiplication).
4. Create the array `[1, 2, 3, 5, 7, 12]` from a Python list, then overwrite the element at index 2 with `10`.
5. Create an array with integers from 3 up to (but not including) 10 using a range-style function.
6. Create an array of 11 evenly spaced numbers between 0 and 100 (inclusive).

In [4]:
# 1. array of 10 zeros
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# 2. array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# 3. array of 10 elements all equal to 2.5
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
# 4. create array, then set index 2 to 10
a = None
a = np.arange(3,11, 2)
a[2:]

array([7, 9])

In [11]:
# 5. integers from 3 up to (not including) 10
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
# 6. 11 evenly spaced numbers between 0 and 100

np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays

1. Create a 5x2 array of zeros.
2. Create the 3x3 array `[[1,2,3],[4,5,6],[7,8,9]]`.
3. Set the element at row 0, column 1 to `20`.
4. Replace the entire row at index 2 with `[1, 1, 1]`.
5. Replace the entire column at index 2 with `[0, 1, 2]`.
6. Print the final array and check it matches what you expected.

In [16]:
# 1. 5x2 array of zeros
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
# 2. build n
n = None
n = np.array([
	np.arange(1,4),
	np.linspace(4,6,3),
	np.arange(7,10)
])
n

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [7]:
# 3. n[0, 1] = 20
n[0,1] = 20
n

array([[ 1., 20.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [10]:
# 4. replace row 2 with [1, 1, 1]
n[2,:] = [1,1,1]
n

array([[ 1., 20.,  1.],
       [ 4.,  5.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
# 5. replace column 2 with [0, 1, 2]
n[:, 2] = [0,1,2]

In [13]:
# 6. print n
n

array([[ 1., 20.,  0.],
       [ 4.,  5.,  1.],
       [ 1.,  1.,  2.]])

## Randomly generated arrays

1. Seed the random generator with `2`, then generate a 5x2 array of random numbers in `[0, 100)` using `np.random.rand`.
2. Re-seed with `2`, then generate a 5x2 array of standard-normal samples with `np.random.randn`.
3. Re-seed with `2`, then generate a 5x2 array of random integers between 0 and 100 (exclusive) with `np.random.randint`.
4. Without re-running the seed, what happens if you call `np.random.rand(5, 2)` again? Try it and think about why.

In [18]:
# 1. seeded rand, scaled to [0, 100)
n = np.random.rand(5, 2)
n * 100

array([[36.26059427, 16.29829968],
       [25.87591439, 47.3103782 ],
       [52.48418031, 22.10099478],
       [35.34441266, 62.97816138],
       [71.83777045,  6.14996059]])

In [22]:
# 2. seeded randn
n = np.random.randn(5, 2)
n * 100

array([[-119.94338665, -130.81202198],
       [  -0.9418282 ,  121.94305193],
       [  27.09608339,  -46.97060478],
       [  -7.81639816, -142.45786825],
       [-102.76354324, -238.532417  ]])

In [26]:
# 3. seeded randint
n = np.random.randint(low=0, high=10000, size=(5,2))
n

array([[ 681, 6930],
       [1952, 9700],
       [5387, 1425],
       [8608, 6225],
       [3097, 3085]], dtype=int32)

In [ ]:
# 4. call rand again without reseeding - observe/explain


## Element-wise operations

1. Create `a = np.arange(5)`.
2. Compute `b = (10 + (a * 2)) ** 2 / 100`.
3. Compute `a / b + 10`.

### Comparison operations

4. Compute the boolean array `a >= 2`.
5. Compute the boolean array `a > b`.
6. Use boolean indexing to select only the elements of `a` where `a > b`.

### Logical operations

7. Using `a` and `b` from above, build a boolean mask that is `True` where `a > 1` **and** `b < 3`, and use it to filter `a`. (Hint: `&`, or `np.logical_and`.)
8. Build a mask that is `True` where `a == 0` **or** `a == 4`, and use it to filter `a`.

In [ ]:
# 1-3. a, b, a / b + 10
a = None
b = None


In [ ]:
# 4-6. comparisons and boolean indexing


In [ ]:
# 7. AND mask


In [ ]:
# 8. OR mask


## Summarizing operations

Using `a` from before:

1. Compute the standard deviation of `a`.
2. Compute the mean and sum of `a`.
3. Using `n` from the multi-dimensional section, compute its minimum and maximum.
4. Bonus: compute the min of `n` along each axis separately (`axis=0` and `axis=1`) and explain the difference in your own words.

In [ ]:
# 1-2. std, mean, sum of a


In [ ]:
# 3. min/max of n


In [ ]:
# 4. bonus: axis=0 vs axis=1


### Next

Linear algebra refresher — practice in `08-linear-algebra-practice.ipynb`.