# ML Zoomcamp 2025 — Module 1 Homework — Solution

Dataset: [Car Fuel Efficiency](https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv)

Homework: [[Courses/machine-learning-zoomcamp/cohorts/2025/01-intro/homework.md]]

## Setup

In [1]:
import numpy as np
import pandas as pd


## Q1. Pandas version

In [2]:
pd.__version__


'3.0.1'

## Getting the data

In [3]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'
df = pd.read_csv(url)
df.head()


,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369


## Q2. Records count

**Answer: 9704**

In [4]:
len(df)


9704

## Q3. Fuel types

**Answer: 2** (`Gasoline`, `Diesel`)

In [5]:
df['fuel_type'].nunique()


2

## Q4. Missing values

**Answer: 4** columns have missing values (`num_cylinders`, `horsepower`, `acceleration`, `num_doors`)

In [6]:
df.isnull().sum()


engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [7]:
(df.isnull().sum() > 0).sum()


np.int64(4)

## Q5. Max fuel efficiency

**Answer: 23.75** (closest option to the actual value ~23.759)

In [8]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()


np.float64(23.759122836520497)

## Q6. Median value of horsepower

**Answer: Yes, it increased** (149.0 → 152.0)

In [9]:
median_before = df['horsepower'].median()
median_before


np.float64(149.0)

In [10]:
mode_value = df['horsepower'].mode()[0]
mode_value


np.float64(152.0)

In [11]:
df['horsepower'] = df['horsepower'].fillna(mode_value)


In [12]:
median_after = df['horsepower'].median()
median_after


np.float64(152.0)

In [13]:
print(f'before: {median_before}, mode: {mode_value}, after: {median_after}')


before: 149.0, mode: 152.0, after: 152.0


## Q7. Sum of weights

**Answer: 0.51** (closest option to the actual value ~0.5188)

In [14]:
asia = df[df['origin'] == 'Asia']
X = asia[['vehicle_weight', 'model_year']].iloc[:7].to_numpy()
X


array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [15]:
XTX = X.T.dot(X)
XTX


array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [16]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv


array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [17]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])


In [18]:
w = XTX_inv.dot(X.T).dot(y)
w


array([0.01386421, 0.5049067 ])

In [19]:
w.sum()


np.float64(0.5187709081074016)

## Summary of answers

| Question | Answer |
|---|---|
| Q1 | (depends on installed Pandas version) |
| Q2 | 9704 |
| Q3 | 2 |
| Q4 | 4 |
| Q5 | 23.75 |
| Q6 | Yes, it increased |
| Q7 | 0.51 |
